apiVersion: v1
kind: ConfigMap
metadata:
  name: api-testnet-casperholders-config
data:
  CASPER_RPC_URL: https://node.testnet.casperholders.com
  ORIGIN: http://localhost:8080,https://testnet.casperholders.io
  PORT: "80"
  DATA_API: https://data.testnet.casperholders.com
  NODE_ENV: "production"
  NETWORK: "casper-test"
  ACCOUNT_INFO_HASH: "2f36a35edcbaabe17aba805e3fae42699a2bb80c2e0c15189756fdc4895356f8"
