apiVersion: v1
kind: Service
metadata:
  name: api-testnet-casperholders-service
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
  selector:
    app: testnet-casperholders-api
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: casperholders-api-db-service-testnet
spec:
  ports:
    - name: casperholders-api-db-service-testnet
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: casperholders-api-db-testnet
---
apiVersion: v1
kind: Service
metadata:
  name: casperholders-api-redis-service-testnet
spec:
  ports:
    - name: casperholders-api-redis-service-testnet
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: casperholders-api-redis-testnet