apiVersion: v1
kind: ConfigMap
metadata:
  name: api-casperholders-config
data:
  CASPER_RPC_URL: https://node.casperholders.com
  ORIGIN: https://casperholders.io,https://www.casperholders.io
  PORT: "80"
