name: testnet

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17

      - name: before_script
        run: yarn install --non-interactive

      - name: script
        run: |
          yarn lint
          yarn build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_php
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: killianh/casperholders:testnet-api

      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
        id: setcontext

      - uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'api-testnet-casperholders'
          manifests: |
            kubernetes/testnet/https.yml
            kubernetes/testnet/issuer.yml
            kubernetes/testnet/config.yml
            kubernetes/testnet/deployment.yml
            kubernetes/testnet/service.yml
            kubernetes/testnet/ingress.yml
            kubernetes/testnet/certificate.yml