name: tests

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17

      - name: install deps
        run: yarn install --non-interactive
      - name: run tests
        run: yarn test
      - uses: codecov/codecov-action@v2